export const WEATHER_ICON_MAP = {
    'Cloudy': "../src/assets/animated/cloudy.svg",
    'Overcast': "../src/assets/animated/cloudy.svg",
    'Moderate snow': "../src/assets/animated/snowy-6.svg",
    'Snow': "../src/assets/animated/snowy-6.svg",
    'Light snow': "../src/assets/animated/snowy-6.svg",
    'Light snow showers': "../src/assets/animated/snowy-6.svg",
    'Heavy rain': "../src/assets/animated/rainy-7.svg",
    'Light rain showers': "../src/assets/animated/rainy-7.svg",
    'Moderate rain': "../src/assets/animated/rainy-7.svg",
    'Light rain shower': "../src/assets/animated/rainy-7.svg",
    'Light freezing rain': "../src/assets/animated/rainy-7.svg",
    'Clear': "../src/assets/animated/day.svg",
    'Sunny': "../src/assets/animated/day.svg",
    'Mist': "../src/assets/animated/mist.svg",
    'Fog': "../src/assets/animated/fog.svg",
    'Freezing fog': "../src/assets/animated/fog.svg",
    'Drizzle': "../src/assets/animated/rainy-4.svg",
    'Rainy': "../src/assets/animated/rainy-4.svg",
    'Light rain': "../src/assets/animated/rainy-4.svg",
    'Light drizzle': "../src/assets/animated/rainy-4.svg",
    'Patchy light drizzle': "../src/assets/animated/rainy-4.svg",
    'Patchy light rain': "../src/assets/animated/rainy-4.svg",
    'Partly cloudy': "../src/assets/animated/partly-cloudy-day.svg",
    'Heavy snow': "../src/assets/animated/extreme-snow.svg",
    'Moderate or heavy snow showers': "../src/assets/animated/extreme-snow.svg",
    'Patchy moderate snow': "../src/assets/animated/extreme-snow.svg",
    'Light sleet': "../src/assets/animated/sleet.svg",
    'Light sleet showers': "../src/assets/animated/sleet.svg",
    'Patchy rain possible': "../src/assets/animated/patchy_rain_possible.svg",
    'Thundery outbreaks possible': "../src/assets/animated/thunderstorms-extreme.svg"
};